# Generated by Django 2.0 on 2018-03-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salaries',
                'ordering': ('id', 'name'),
                'verbose_name_plural': 'salaries',
                'verbose_name': 'salary',
            },
        ),
    ]
